### ISSUE TITLE
ruruku should be able to serve files 

### ISSUE THREAD

**Issue by bwl21** [32leaves/ruruku#43]
# UseCase

I play around with ruruku to monitor tests of zupfnoter (https://github.com/bwl21/zupfnoter/issues/245). 

As a developer I create testcases before I make changes in Zupfnoter. As a "release manager"  I am using a scripting environment (rspec) to generate diff of all testcase-pdfs and messages produced by the app. But I need a quick way to investigate these diffs and collect findings. This is where ruruku comes in.

# Solution approach

* let the testsuite (rspec) generate a ruruku testplan. In the steps section of a particular test refer to or even embed the aforehead mentioned diff files.
* go through all tests in ruruku and  do the investigation. Thereby show the test results. It could look like this:

![untitled](https://user-images.githubusercontent.com/2022976/49455295-3005e980-f7e7-11e8-8d58-c198da041e75.jpg)

I have created this screenshot by a testcase like tis

```yaml
- description: "./test-source/083_Der_Mirjambrunnen_Bernhard.abc"
  group: ''
  id: "./test-source/083"
  minTesterCount: 0
  mustPass: false
  name: mal schaun ./test-source/083_Der_Mirjambrunnen_Bernhard.abc
  steps: "\n\n## investigate ./test-source/083_Der_Mirjambrunnen_Bernhard.abc\n\n<img
    src=\"http://localhost:3000/test-output/083_Der_Mirjambrunnen_Bernhard_-test_a3.png\"
    alt=\"drawing\" width=\"100%\"/>\n<img src=\"http://localhost:3000/test-diff/083_Der_Mirjambrunnen_Bernhard.diff.png\"
    alt=\"drawing\" width=\"100%\"/>\n\n  "
- description: "./test-source/1003_Jumplines.abc"
```

As you see I had to setup another webserver to serve the outputfiles of my testsuite. It would be great if ruruku could serve these files with an url resolved relative to the position of the testplan.yaml. It would even be better if testplan.yaml could specify the root of the server files.
