### ISSUE TITLE
handling changing multiple tests if they start with the same id

### ISSUE THREAD

**Issue by bwl21** [32leaves/ruruku#70]
Using the following testplan

```yaml
id: "1"
name: Das ist test 1
description: ""
case:
- id: "1"
  name: test 1
  group: one
  description: ""
  steps: ""
  mustpass: false
  mintestercount: 0
- id: "10"
  name: test 10
  group: one
  description: ""
  steps: ""
  mustpass: false
  mintestercount: 0
- id: "100"
  name: test 100
  group: one
  description: ""
  steps: ""
  mustpass: false
  mintestercount: 0
```

and confirming all three cases, I get

![screenshot_1301](https://user-images.githubusercontent.com/2022976/50541261-19fb0700-0ba2-11e9-9106-01e897404761.jpg)
